services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/app.py
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./src:/app  # Mappa la cartella locale 'src' alla cartella '/app' nel contenitore
    networks:
      - flask_network

  mongodb:
    image: mongo:latest
    container_name: mongodbdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - flask_network

volumes:
  mongo_data:

networks:
  flask_network:
    driver: bridge
